
<div class="view">
<h1>Details of <?php echo $this->model->getTitle();?></h1><br />
<span class="details"><?php echo $this->model->getDescription();?></span><br />
<span>Verified: <?php echo ($this->model->getVerified()) ? 'Yes' : 'No' ; ?></span>
<?php if(!$this->model->getVerified()):?>
	<?php $url = $this->url(
		array('controller'=>'incident', 'action'=>'verify', 'id' => $this->model->getId()),
		'default', true);?>
	<span class="verifylink"><a href="<?php echo $url ?>
		">Verify incident</a></span>
<?php endif;?>
</div>